name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Start services with docker-compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "waiting for postgres..."
            sleep 1
          done

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: order_processor
        run: npm run migrate

      - name: Run E2E tests
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: order_processor
        run: npm run test:e2e
