name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: order_processor
        ports:
          - 5432:5432
        options: >- # this is a multi-line string
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Wait for PostgreSQL
        run: while ! pg_isready -h localhost -p 5432; do sleep 1; done;

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npm run migrate

      - name: Run E2E tests
        run: npm run test:e2e
